import './globals.css'
import { Inter, Playfair_Display, Fira_Code } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const playfair = Playfair_Display({ 
  subsets: ['latin'],
  variable: '--font-playfair'
})
const firaCode = Fira_Code({
  subsets: ['latin'],
  variable: '--font-fira-code'
})

export const metadata = {
  title: 'My Portoflio',
  description: 'Generated by Disha',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${playfair.variable} ${firaCode.variable}`}>{children}</body>
    </html>
  )
}
